import type { GlobeDestination, ArcData } from "@/types";

// Kerala hub coordinates
const KERALA_LAT = 9.9312;
const KERALA_LNG = 76.2673;

export const destinations: GlobeDestination[] = [
  // India destinations (well-spaced selection)
  {
    id: "delhi",
    name: "Delhi",
    tagline: "Heart of India",
    description:
      "A sprawling capital where Mughal-era grandeur meets modern energy — from the Red Fort to bustling Chandni Chowk.",
    lat: 28.6139,
    lng: 77.209,
    highlights: ["Red Fort", "Qutub Minar", "India Gate"],
  },
  {
    id: "jaipur",
    name: "Jaipur, Rajasthan",
    tagline: "The Pink City",
    description:
      "Royal palaces, vibrant bazaars, and majestic forts painted in the warm hues of Rajasthan.",
    lat: 26.9124,
    lng: 75.7873,
    highlights: ["Hawa Mahal", "Amber Fort", "City Palace"],
  },
  {
    id: "goa",
    name: "Goa",
    tagline: "Sun, Sand & Soul",
    description:
      "Golden beaches, Portuguese heritage, and legendary nightlife on India's tropical west coast.",
    lat: 15.2993,
    lng: 74.124,
    highlights: ["Baga Beach", "Basilica of Bom Jesus", "Dudhsagar Falls"],
  },
  {
    id: "kerala",
    name: "Kerala",
    tagline: "God's Own Country",
    description:
      "Serene backwaters, lush hill stations, and Ayurvedic traditions in India's greenest state.",
    lat: 10.8505,
    lng: 76.2711,
    highlights: ["Alleppey Backwaters", "Munnar Tea Gardens", "Fort Kochi"],
  },
  {
    id: "varanasi",
    name: "Varanasi",
    tagline: "The Eternal City",
    description:
      "One of the world's oldest living cities — sacred ghats, evening aartis, and deep spiritual energy on the banks of the Ganges.",
    lat: 25.3176,
    lng: 82.9739,
    highlights: [
      "Dashashwamedh Ghat",
      "Kashi Vishwanath",
      "Boat Ride at Dawn",
    ],
  },
  {
    id: "leh-ladakh",
    name: "Leh-Ladakh",
    tagline: "Land of High Passes",
    description:
      "Breathtaking Himalayan landscapes, ancient monasteries, and some of the highest motorable roads on earth.",
    lat: 34.1526,
    lng: 77.5771,
    highlights: ["Pangong Lake", "Nubra Valley", "Khardung La Pass"],
  },
  {
    id: "andaman",
    name: "Andaman Islands",
    tagline: "Tropical Island Escape",
    description:
      "Pristine white-sand beaches, turquoise waters, and vibrant coral reefs in the Bay of Bengal.",
    lat: 11.7401,
    lng: 92.6586,
    highlights: ["Radhanagar Beach", "Cellular Jail", "Scuba at Havelock"],
  },
  // International destinations
  {
    id: "singapore",
    name: "Singapore",
    tagline: "The Lion City",
    description:
      "A dazzling city-state where futuristic architecture, world-class dining, and lush gardens blend seamlessly.",
    lat: 1.3521,
    lng: 103.8198,
    highlights: ["Marina Bay Sands", "Gardens by the Bay", "Sentosa Island"],
  },
  {
    id: "malaysia",
    name: "Kuala Lumpur, Malaysia",
    tagline: "Where Cultures Converge",
    description:
      "A vibrant melting pot of Malay, Chinese, and Indian cultures crowned by the iconic Petronas Towers.",
    lat: 3.139,
    lng: 101.6869,
    highlights: ["Petronas Towers", "Batu Caves", "Langkawi Island"],
  },
  {
    id: "bali",
    name: "Bali, Indonesia",
    tagline: "Island of the Gods",
    description:
      "Discover tropical paradise with ancient temples, terraced rice paddies, and pristine beaches.",
    lat: -8.3405,
    lng: 115.092,
    highlights: ["Ubud Rice Terraces", "Tanah Lot Temple", "Seminyak Beach"],
  },
  {
    id: "thailand",
    name: "Bangkok, Thailand",
    tagline: "City of Angels",
    description:
      "Glittering temples, floating markets, and legendary street food in Southeast Asia's most electrifying capital.",
    lat: 13.7563,
    lng: 100.5018,
    highlights: ["Grand Palace", "Chatuchak Market", "Phi Phi Islands"],
  },
  {
    id: "vietnam",
    name: "Hanoi, Vietnam",
    tagline: "The Enchanting Capital",
    description:
      "Ancient charm meets vibrant energy — from the Old Quarter's bustling lanes to the serene waters of Ha Long Bay.",
    lat: 21.0285,
    lng: 105.8542,
    highlights: ["Ha Long Bay", "Hoi An Old Town", "Sapa Rice Terraces"],
  },
  {
    id: "azerbaijan",
    name: "Baku, Azerbaijan",
    tagline: "Land of Fire",
    description:
      "A striking blend of medieval old town and ultra-modern architecture on the shores of the Caspian Sea.",
    lat: 40.4093,
    lng: 49.8671,
    highlights: ["Flame Towers", "Old City (Icherisheher)", "Heydar Aliyev Center"],
  },
  {
    id: "georgia",
    name: "Tbilisi, Georgia",
    tagline: "Where Europe Meets Asia",
    description:
      "Cobblestone streets, ancient churches, and a thriving wine culture nestled between the Caucasus Mountains.",
    lat: 41.7151,
    lng: 44.8271,
    highlights: ["Old Town Tbilisi", "Kazbegi Mountains", "Georgian Wine Country"],
  },
  {
    id: "oman",
    name: "Muscat, Oman",
    tagline: "Jewel of Arabia",
    description:
      "Dramatic fjords, golden deserts, and timeless souqs in the most welcoming corner of the Arabian Peninsula.",
    lat: 23.588,
    lng: 58.3829,
    highlights: ["Sultan Qaboos Mosque", "Wadi Shab", "Wahiba Sands"],
  },
  {
    id: "uae",
    name: "Dubai, UAE",
    tagline: "City of the Future",
    description:
      "From the world's tallest tower to vast golden deserts — a playground of luxury and innovation.",
    lat: 25.2048,
    lng: 55.2708,
    highlights: ["Burj Khalifa", "Palm Jumeirah", "Desert Safari"],
  },
  {
    id: "srilanka",
    name: "Sri Lanka",
    tagline: "Pearl of the Indian Ocean",
    description:
      "Ancient ruins, misty tea hills, golden beaches, and abundant wildlife on a compact tropical island.",
    lat: 7.8731,
    lng: 80.7718,
    highlights: ["Sigiriya Rock", "Ella Train Ride", "Galle Fort"],
  },
];

export const travelArcs: ArcData[] = [
  // Kerala to Indian destinations
  {
    order: 1,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 28.6139,
    endLng: 77.209,
    arcAlt: 0.15,
    color: "#f58220",
  },
  {
    order: 2,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 15.2993,
    endLng: 74.124,
    arcAlt: 0.08,
    color: "#3b82f6",
  },
  {
    order: 3,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 34.1526,
    endLng: 77.5771,
    arcAlt: 0.18,
    color: "#6366f1",
  },
  {
    order: 4,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 25.3176,
    endLng: 82.9739,
    arcAlt: 0.12,
    color: "#3b82f6",
  },
  {
    order: 5,
    startLat: 28.6139,
    startLng: 77.209,
    endLat: 26.9124,
    endLng: 75.7873,
    arcAlt: 0.05,
    color: "#f58220",
  },
  {
    order: 6,
    startLat: 28.6139,
    startLng: 77.209,
    endLat: 34.1526,
    endLng: 77.5771,
    arcAlt: 0.08,
    color: "#6366f1",
  },
  {
    order: 7,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 11.7401,
    endLng: 92.6586,
    arcAlt: 0.12,
    color: "#f58220",
  },
  // Kerala to international destinations
  {
    order: 2,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 1.3521,
    endLng: 103.8198,
    arcAlt: 0.25,
    color: "#f58220",
  },
  {
    order: 3,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 3.139,
    endLng: 101.6869,
    arcAlt: 0.22,
    color: "#06b6d4",
  },
  {
    order: 4,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: -8.3405,
    endLng: 115.092,
    arcAlt: 0.3,
    color: "#3b82f6",
  },
  {
    order: 5,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 13.7563,
    endLng: 100.5018,
    arcAlt: 0.2,
    color: "#6366f1",
  },
  {
    order: 6,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 21.0285,
    endLng: 105.8542,
    arcAlt: 0.25,
    color: "#f58220",
  },
  {
    order: 7,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 40.4093,
    endLng: 49.8671,
    arcAlt: 0.25,
    color: "#06b6d4",
  },
  {
    order: 8,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 41.7151,
    endLng: 44.8271,
    arcAlt: 0.27,
    color: "#3b82f6",
  },
  {
    order: 9,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 23.588,
    endLng: 58.3829,
    arcAlt: 0.15,
    color: "#6366f1",
  },
  {
    order: 10,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 25.2048,
    endLng: 55.2708,
    arcAlt: 0.18,
    color: "#f58220",
  },
  {
    order: 11,
    startLat: KERALA_LAT,
    startLng: KERALA_LNG,
    endLat: 7.8731,
    endLng: 80.7718,
    arcAlt: 0.06,
    color: "#06b6d4",
  },
  // Inter-destination arcs
  {
    order: 12,
    startLat: 1.3521,
    startLng: 103.8198,
    endLat: 3.139,
    endLng: 101.6869,
    arcAlt: 0.04,
    color: "#3b82f6",
  },
  {
    order: 13,
    startLat: 13.7563,
    startLng: 100.5018,
    endLat: 21.0285,
    endLng: 105.8542,
    arcAlt: 0.1,
    color: "#6366f1",
  },
  {
    order: 14,
    startLat: 25.2048,
    startLng: 55.2708,
    endLat: 23.588,
    endLng: 58.3829,
    arcAlt: 0.04,
    color: "#f58220",
  },
  {
    order: 1,
    startLat: 40.4093,
    startLng: 49.8671,
    endLat: 41.7151,
    endLng: 44.8271,
    arcAlt: 0.06,
    color: "#06b6d4",
  },
  {
    order: 2,
    startLat: 1.3521,
    startLng: 103.8198,
    endLat: -8.3405,
    endLng: 115.092,
    arcAlt: 0.12,
    color: "#3b82f6",
  },
];
